version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    # don't make PRs for regular dependency things, just security updates
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    # don't make PRs for regular dependency things, just security updates
    open-pull-requests-limit: 0
