brew "gh"
brew "ghostscript"
brew "imagemagick"
# tap "AdoptOpenJDK/openjdk"
# cask "adoptopenjdk"
brew "pipx"
brew "poppler"
brew "postgis"
brew "rbenv"
brew "yarn"
brew "node@18"
cask "aptible"
brew "libyaml"
