name: vita-min

services:
  db:
    container_name: db
    image: postgis/postgis:13-3.4-alpine
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
  pgadmin:
    container_name: pgadmin
    profiles: ["pgadmin"]
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050
    depends_on:
      - rails
  jobs:
    container_name: jobs
    image: ruby:3.2.2
    volumes:
      - ./:/app
    command: bin/rails jobs:work
    depends_on:
      - rails
    environment:
      - RAILS_DB_HOST=db
      - RAILS_DB_USERNAME=postgres
      - RAILS_DB_PORT=5432
      - RAILS_DB_PASSWORD=password
  rails:
    container_name: rails
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 9888:9888
    depends_on:
      - db
    links:
      - db
    environment:
      - "RUN_MIGRATIONS=${RUN_MIGRATIONS}"
      - RAILS_CAPYBARA_SERVER_HOST=rails
      - RAILS_DB_HOST=db
      - RAILS_DB_USERNAME=postgres
      - RAILS_DB_PORT=5432
      - RAILS_DB_PASSWORD=password
  chrome:
    container_name: chrome
    image: selenium/standalone-chrome:4.15.0 # this version should match that of the selenium-webdriver gem (see Gemfile)
    ports:
      - 4444:4444
volumes:
  database: