name: vita-min

# TODO: debug why db service does not start before rails service
# For now, db must be manually started before rails

services:
  db:
    container_name: db
    image: postgis/postgis:13-3.4-alpine
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 5
      timeout: 10s
  pgadmin:
    container_name: pgadmin
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050
    depends_on:
      - db
  jobs:
    container_name: jobs
    image: ruby:3.2.2
    volumes:
      - ./:/app
    command: bin/rails jobs:work
    depends_on:
      - rails
    environment:
      - RAILS_DB_HOST=db
      - RAILS_DB_USERNAME=postgres
      - RAILS_DB_PORT=5432
      - RAILS_DB_PASSWORD=password
  rails:
    container_name: rails
    image: ruby:3.2.2
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    environment:
      - "RAILS_ENV=${RAILS_ENV:-development}"
      - RAILS_DB_HOST=db
      - RAILS_DB_USERNAME=postgres
      - RAILS_DB_PORT=5432
      - RAILS_DB_PASSWORD=password
volumes:
  database: