development:
  adapter: postgresql

staging:
  adapter: postgresql

heroku:
  adapter: postgresql

demo:
  adapter: <%= ENV["REDIS_URL"].present? ? "redis" : "postgresql" %>
  url: <%= ENV.fetch("REDIS_URL") %>

production:
  adapter: postgresql

test:
  adapter: test