development:
  adapter: postgresql

staging:
  adapter: postgresql

heroku:
  adapter: postgresql

demo:
  adapter: <%= ENV["REDIS_URL"].present? ? "redis" : "postgresql" %>
  url: <%= ENV["REDIS_URL"] %>

production:
  adapter: <%= ENV["REDIS_URL"].present? ? "redis" : "postgresql" %>
  url: <%= ENV["REDIS_URL"] %>

test:
  adapter: test