development:
  adapter: postgresql

staging:
  adapter: postgresql

heroku:
  adapter: postgresql

demo:
  adapter: redis
  url: <%= ENV.fetch('MINI_PROFILER_REDIS_URL') %>

production:
  adapter: postgresql

test:
  adapter: test