development:
  adapter: postgresql

staging:
  adapter: postgresql

heroku:
  adapter: postgresql

demo:
  adapter: redis
  url: <%= ENV.fetch("MINI_PROFILER_REDIS_URL", "redis://localhost:6379/0") %>

production:
  adapter: postgresql

test:
  adapter: test