deploy_default: &deploy_default
  service: S3
  access_key_id: <%= EnvironmentalCredentials['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= EnvironmentalCredentials['AWS_SECRET_ACCESS_KEY'] %>
  region: us-east-1

test:
  service: GyrDisk
  # Use /tmp which is autocleared periodically on macOS
  root: "/tmp/vita-min-test-storage"

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
s3_prod:
  <<: *deploy_default
  bucket: vita-min-prod-docs

s3_staging:
  <<: *deploy_default
  bucket: vita-min-staging-docs

s3_demo:
  <<: *deploy_default
  bucket: vita-min-demo-docs

s3_heroku:
  <<: *deploy_default
  bucket: vita-min-heroku-docs

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= EnvironmentalCredentials['AZURE_STORAGE_STORAGE_ACCESS_KEY'] %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
