truncate table anonymized_diy_intake_csv_extracts
             , anonymized_intake_csv_extracts
             , idme_users
             , active_storage_attachments
             , active_storage_blobs
             , clients
             , dependents
             , diy_intakes
             , documents
             , documents_requests
             , delayed_jobs
             , incoming_emails
             , incoming_text_messages
             , intakes
             , notes
             , outgoing_emails
             , outgoing_text_messages
             , system_notes
             , tax_returns
             , users
             , users_vita_partners
             , intake_site_drop_offs
             , stimulus_triages
             , ticket_statuses;