name: Security Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security-scan:
    uses: codeforamerica/github-actions/.github/workflows/security-scan.yml@main
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    with:
      path: "./"
  sast-scan:
    uses: codeforamerica/github-actions/.github/workflows/sast-scan.yml@rd/opengrep
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    with:
      path: "./"
      ruby: true
